import { useMemo, useState } from "react";
import "@/App.css";
import {
  AlertTriangle, ArrowRight, BarChart3, BookOpen, CalendarDays, Check, CheckSquare,
  ChevronDown, ClipboardList, FileDown, FileText, GraduationCap, LayoutDashboard,
  LogOut, Menu, MoreHorizontal, Plus, Printer, Save, School, Search, Settings,
  ShieldCheck, Sparkles, Users, X, BookMarked
} from "lucide-react";

const NAV = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard },
  { id: "jadwal", label: "Jadwal Mengajar", icon: CalendarDays },
  { id: "absensi", label: "Absensi Siswa", icon: CheckSquare },
  { id: "nilai", label: "Nilai Siswa", icon: GraduationCap },
  { id: "jurnal", label: "Jurnal Mengajar", icon: BookMarked },
  { id: "rekap", label: "Rekap & Cetak", icon: Printer },
];
const ADMIN_NAV = [
  { id: "guru", label: "Kelola Guru", icon: Users },
  { id: "kelas", label: "Kelola Kelas", icon: School },
  { id: "siswa", label: "Kelola Siswa", icon: Users },
  { id: "mapel", label: "Kelola Mapel", icon: BookOpen },
  { id: "pengaturan", label: "Pengaturan", icon: Settings },
];
const students = ["Alya Putri", "Bagas Pratama", "Citra Lestari", "Daffa Ramadhan", "Eka Salsabila", "Fajar Nugraha"];
const classes = ["7A", "7B", "8A", "9A"];
const subjects = ["Matematika", "Bahasa Indonesia", "IPA", "Informatika"];

function App() {
  const [loggedIn, setLoggedIn] = useState(() => localStorage.getItem("absenspg-login") === "true");
  const [active, setActive] = useState("dashboard");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [toast, setToast] = useState("");
  const [attendance, setAttendance] = useState(Object.fromEntries(students.map((s) => [s, "H"])));
  const [grades, setGrades] = useState(Object.fromEntries(students.map((s, i) => [s, [86, 78, 92, 88, 81, 95][i]])));
  const [settings, setSettings] = useState({ school: "SMP PGRI Gandoang", address: "Jl. Raya Gandoang No. 12", principal: "Drs. Ahmad Fauzi", nip: "197001011995011001" });

  const showToast = (message) => { setToast(message); window.setTimeout(() => setToast(""), 2600); };
  const navigate = (id) => { setActive(id); setMobileOpen(false); };
  if (!loggedIn) return <Login onLogin={() => { localStorage.setItem("absenspg-login", "true"); setLoggedIn(true); }} />;

  return (
    <div className="app-shell">
      <aside className={`sidebar ${mobileOpen ? "open" : ""}`} data-testid="sidebar-navigation">
        <div className="brand"><div className="brand-mark"><GraduationCap size={23} /></div><div><strong>AbsenSPG</strong><span>Teacher workspace</span></div></div>
        <div className="profile"><div className="avatar">AF</div><div><strong data-testid="current-user-name">Ahmad Fauzi</strong><span data-testid="current-user-role">Administrator</span></div><ShieldCheck size={16} className="profile-check" /></div>
        <nav className="nav-list" aria-label="Navigasi utama">
          <div className="nav-caption">Workspace</div>
          {NAV.map((item) => <NavItem key={item.id} item={item} active={active} onClick={navigate} />)}
          <div className="nav-caption admin-caption">Administration</div>
          {ADMIN_NAV.map((item) => <NavItem key={item.id} item={item} active={active} onClick={navigate} />)}
        </nav>
        <div className="sidebar-bottom"><div className="backup-chip"><span className="pulse-dot" /> Backup otomatis aktif <ChevronDown size={14} /></div><button className="logout-button" data-testid="logout-button" onClick={() => { localStorage.removeItem("absenspg-login"); setLoggedIn(false); }}><LogOut size={16} /> Keluar</button></div>
      </aside>
      {mobileOpen && <button className="mobile-scrim" data-testid="mobile-menu-close" onClick={() => setMobileOpen(false)} aria-label="Tutup menu" />}
      <main className="main-content">
        <header className="topbar"><button className="icon-button mobile-menu-button" data-testid="mobile-menu-button" onClick={() => setMobileOpen(true)} aria-label="Buka menu"><Menu size={20} /></button><div className="crumb"><span>SMP PGRI Gandoang</span><ArrowRight size={14} /><strong>{NAV.concat(ADMIN_NAV).find((n) => n.id === active)?.label || "Dashboard"}</strong></div><div className="top-actions"><button className="icon-button" data-testid="global-search-button" aria-label="Cari"><Search size={18} /></button><div className="date-badge" data-testid="today-date"><CalendarDays size={15} /> Senin, 12 Mei 2025</div><div className="mini-avatar">AF</div></div></header>
        <div className="page-wrap">{active === "dashboard" && <Dashboard navigate={navigate} />} {active === "absensi" && <Attendance attendance={attendance} setAttendance={setAttendance} onSave={() => showToast("Absensi 7A berhasil disimpan")} />} {active === "nilai" && <Grades grades={grades} setGrades={setGrades} onSave={() => showToast("Nilai siswa berhasil disimpan")} />} {active === "jadwal" && <Schedule onSave={() => showToast("Jadwal baru ditambahkan")} />} {active === "jurnal" && <Journal onSave={() => showToast("Jurnal pembelajaran tersimpan")} />} {active === "rekap" && <Reports onExport={() => showToast("Rekap siap diunduh")} />} {active === "guru" && <Master title="Kelola Guru" icon={Users} rows={["Ahmad Fauzi", "Siti Nurhaliza", "Dedi Kurniawan"]} addLabel="Tambah guru" onSave={() => showToast("Data guru diperbarui")} />} {active === "kelas" && <Master title="Kelola Kelas" icon={School} rows={classes} addLabel="Tambah kelas" onSave={() => showToast("Kelas baru ditambahkan")} />} {active === "siswa" && <Master title="Kelola Siswa" icon={Users} rows={students} addLabel="Tambah siswa" onSave={() => showToast("Data siswa diperbarui")} />} {active === "mapel" && <Master title="Kelola Mata Pelajaran" icon={BookOpen} rows={subjects} addLabel="Tambah mapel" onSave={() => showToast("Mata pelajaran ditambahkan")} />} {active === "pengaturan" && <SettingsView settings={settings} setSettings={setSettings} onSave={() => showToast("Pengaturan sekolah tersimpan")} />}</div>
      </main>
      {toast && <div className="toast" data-testid="success-toast"><Check size={16} /> {toast}</div>}
    </div>
  );
}

function Login({ onLogin }) { const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); return <div className="login-page"><div className="login-visual"><div className="visual-copy"><span className="eyebrow"><Sparkles size={14} /> Ruang kerja guru</span><h1>Semua kelas.<br /><em>Satu kendali.</em></h1><p>Kelola kehadiran, nilai, jadwal, dan jurnal pembelajaran dengan lebih tenang.</p></div><div className="visual-footer">SMP PGRI Gandoang <span>•</span> Teacher Administration</div></div><div className="login-panel"><div className="login-brand"><div className="brand-mark"><GraduationCap size={24} /></div><span>AbsenSPG</span></div><div className="login-content"><span className="eyebrow">Selamat datang kembali</span><h2>Masuk ke ruang kerja</h2><p className="muted">Gunakan akun guru atau administrator Anda.</p><form onSubmit={(e) => { e.preventDefault(); if (!username || !password) return setError("Username dan password wajib diisi."); onLogin(); }}><label>Username<input data-testid="login-username-input" value={username} onChange={(e) => setUsername(e.target.value)} placeholder="Masukkan username" /></label><label>Password<input data-testid="login-password-input" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Masukkan password" /></label>{error && <div className="form-error" data-testid="login-error">{error}</div>}<button className="primary-button login-submit" data-testid="login-submit-button">Masuk ke dashboard <ArrowRight size={17} /></button></form><p className="login-note">Demo: isi username dan password apa saja</p></div></div></div>; }
function NavItem({ item, active, onClick }) { const Icon = item.icon; return <button className={`nav-item ${active === item.id ? "active" : ""}`} data-testid={`nav-${item.id}`} onClick={() => onClick(item.id)}><Icon size={17} /><span>{item.label}</span>{active === item.id && <span className="nav-active-dot" />}</button>; }
function PageTitle({ eyebrow, title, description, action }) { return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1 data-testid="page-title">{title}</h1><p>{description}</p></div>{action}</div>; }
function Dashboard({ navigate }) { return <><PageTitle eyebrow="Senin, 12 Mei 2025" title="Selamat pagi, Ahmad" description="Berikut ringkasan kegiatan mengajar Anda hari ini." action={<button className="primary-button" data-testid="dashboard-attendance-cta" onClick={() => navigate("absensi")}><CheckSquare size={17} /> Isi absensi</button>} /><div className="stat-grid"><Stat label="Kelas diampu" value="4" change="+1 dari semester lalu" icon={School} color="green" /><Stat label="Siswa aktif" value="126" change="98% data terisi" icon={Users} color="amber" /><Stat label="Rata-rata kehadiran" value="94,8%" change="+2,4% bulan ini" icon={BarChart3} color="blue" /><Stat label="Jurnal tersimpan" value="18" change="3 perlu dilengkapi" icon={BookMarked} color="rose" /></div><div className="dashboard-grid"><section className="panel schedule-panel"><PanelHeading title="Jadwal hari ini" subtitle="Senin, 12 Mei 2025" action={<button className="text-button" data-testid="dashboard-schedule-link" onClick={() => navigate("jadwal")}>Lihat semua <ArrowRight size={14} /></button>} /><div className="timeline"><TimelineItem time="07.00 — 08.20" classNameName="7A" subject="Matematika" room="Ruang 3" active /><TimelineItem time="09.00 — 10.20" classNameName="8A" subject="Matematika" room="Ruang 5" /><TimelineItem time="11.00 — 12.20" classNameName="9A" subject="Informatika" room="Lab Komputer" /></div></section><section className="panel attention-panel"><PanelHeading title="Perlu perhatian" subtitle="Absensi bulan ini" action={<AlertTriangle size={18} className="warning-icon" />} /><div className="attention-callout"><div className="attention-number">7</div><div><strong>siswa sering tidak hadir</strong><p>Lebih dari 3 kali alpa bulan ini</p></div></div>{["Raka Firmansyah", "Nabila Putri", "Rizky Maulana"].map((name, i) => <div className="attention-row" key={name}><div className="student-avatar">{name.split(" ").map((x) => x[0]).join("")}</div><span>{name}</span><b>{4 - i}x alpa</b></div>)}<button className="outline-button" data-testid="view-attention-button" onClick={() => navigate("rekap")}>Buka rekap absensi <ArrowRight size={15} /></button></section></div><section className="quick-section"><div className="section-heading"><div><span className="eyebrow">Akses cepat</span><h2>Mulai dari sini</h2></div><span className="muted">Pekerjaan rutin Anda, lebih ringkas.</span></div><div className="quick-grid"><QuickAction icon={CheckSquare} title="Absensi siswa" text="Catat kehadiran kelas" onClick={() => navigate("absensi")} testid="quick-attendance" /><QuickAction icon={GraduationCap} title="Input nilai" text="Kelola nilai formatif" onClick={() => navigate("nilai")} testid="quick-grades" /><QuickAction icon={BookMarked} title="Jurnal mengajar" text="Simpan refleksi kelas" onClick={() => navigate("jurnal")} testid="quick-journal" /></div></section></>; }
function Stat({ label, value, change, icon: Icon, color }) { return <div className="stat-card" data-testid={`stat-${label.toLowerCase().replaceAll(" ", "-")}`}><div className={`stat-icon ${color}`}><Icon size={19} /></div><div><span>{label}</span><strong>{value}</strong><small>{change}</small></div></div>; }
function PanelHeading({ title, subtitle, action }) { return <div className="panel-heading"><div><h2>{title}</h2><span>{subtitle}</span></div>{action}</div>; }
function TimelineItem({ time, classNameName, subject, room, active }) { return <div className={`timeline-item ${active ? "current" : ""}`}><div className="time">{time}</div><div className="timeline-line"><span /></div><div className="lesson"><div><strong>{subject}</strong><span>{classNameName} · {room}</span></div>{active && <span className="now-badge">Sedang berlangsung</span>}</div></div>; }
function QuickAction({ icon: Icon, title, text, onClick, testid }) { return <button className="quick-action" data-testid={testid} onClick={onClick}><div className="quick-icon"><Icon size={21} /></div><div><strong>{title}</strong><span>{text}</span></div><ArrowRight size={17} /></button>; }
function FormShell({ children, title, subtitle, onSave, saveLabel = "Simpan perubahan" }) { return <section className="panel form-panel"><PanelHeading title={title} subtitle={subtitle} />{children}<div className="form-actions"><button className="primary-button" data-testid="form-save-button" onClick={onSave}><Save size={16} /> {saveLabel}</button></div></section>; }
function Select({ label, children, testid }) { return <label className="field">{label}<select data-testid={testid}>{children}</select></label>; }
function Attendance({ attendance, setAttendance, onSave }) { return <><PageTitle eyebrow="Kegiatan mengajar" title="Absensi siswa" description="Catat kehadiran siswa tanpa pengulangan data." action={<button className="secondary-button" data-testid="attendance-history-button"><FileText size={16} /> Riwayat absensi</button>} /><div className="filter-grid panel"><label className="field">Tanggal<input data-testid="attendance-date-input" type="date" defaultValue="2025-05-12" /></label><Select label="Kelas" testid="attendance-class-select"><option>7A</option><option>7B</option><option>8A</option></Select><Select label="Mata pelajaran" testid="attendance-subject-select"><option>Matematika</option><option>IPA</option></Select><button className="secondary-button filter-button" data-testid="attendance-load-button"><Search size={16} /> Tampilkan siswa</button></div><section className="panel roster-panel"><PanelHeading title="Kelas 7A · Matematika" subtitle="Senin, 12 Mei 2025 · 31 siswa" action={<div className="status-legend"><span><i className="status-dot hadir" /> Hadir</span><span><i className="status-dot sakit" /> Sakit</span><span><i className="status-dot izin" /> Izin</span><span><i className="status-dot alpa" /> Alpa</span></div>} /><div className="table-wrap"><table><thead><tr><th>No</th><th>Nama siswa</th><th>Status kehadiran</th><th>Catatan</th></tr></thead><tbody>{students.map((student, i) => <tr key={student}><td>{String(i + 1).padStart(2, "0")}</td><td><div className="name-cell"><span className="student-avatar">{student.split(" ").map((x) => x[0]).join("")}</span><strong>{student}</strong></div></td><td><div className="status-buttons">{[["H", "Hadir", "hadir"], ["S", "Sakit", "sakit"], ["I", "Izin", "izin"], ["A", "Alpa", "alpa"]].map(([code, name, style]) => <button key={code} className={`${style} ${attendance[student] === code ? "selected" : ""}`} data-testid={`attendance-${i + 1}-${code.toLowerCase()}`} onClick={() => setAttendance({ ...attendance, [student]: code })}>{code}<span>{name}</span></button>)}</div></td><td><input className="table-input" data-testid={`attendance-note-${i + 1}`} placeholder="Tambah catatan" /></td></tr>)}</tbody></table></div><div className="roster-footer"><span><Check size={15} /> {Object.values(attendance).filter((x) => x === "H").length} siswa hadir</span><button className="primary-button" data-testid="attendance-save-button" onClick={onSave}><Save size={16} /> Simpan absensi</button></div></section></>; }
function Grades({ grades, setGrades, onSave }) { return <><PageTitle eyebrow="Kegiatan mengajar" title="Nilai siswa" description="Kelola penilaian formatif dan sumatif dalam satu tempat." action={<button className="secondary-button" data-testid="grades-import-button"><FileDown size={16} /> Impor Excel</button>} /><div className="filter-grid panel grades-filter"><label className="field">Tanggal<input data-testid="grades-date-input" type="date" defaultValue="2025-05-12" /></label><Select label="Kelas" testid="grades-class-select"><option>7A</option><option>7B</option></Select><Select label="Mata pelajaran" testid="grades-subject-select"><option>Matematika</option><option>IPA</option></Select><Select label="Jenis penilaian" testid="grades-type-select"><option>Formatif</option><option>Sumatif Lingkup Materi</option><option>Sumatif Tengah Semester</option></Select></div><section className="panel roster-panel"><PanelHeading title="Penilaian formatif · Aljabar" subtitle="Kelas 7A · Tes tertulis" action={<span className="saved-badge"><Check size={14} /> Draft tersimpan</span>} /><div className="table-wrap"><table><thead><tr><th>No</th><th>Nama siswa</th><th>Nilai (0—100)</th><th>Predikat</th></tr></thead><tbody>{students.map((student, i) => { const grade = Number(grades[student]); return <tr key={student}><td>{String(i + 1).padStart(2, "0")}</td><td><div className="name-cell"><span className="student-avatar">{student.split(" ").map((x) => x[0]).join("")}</span><strong>{student}</strong></div></td><td><input className="grade-input" data-testid={`grade-input-${i + 1}`} type="number" min="0" max="100" value={grade} onChange={(e) => setGrades({ ...grades, [student]: e.target.value })} /></td><td><span className={`grade-pill ${grade >= 85 ? "excellent" : grade >= 75 ? "good" : "needs"}`}>{grade >= 85 ? "Sangat baik" : grade >= 75 ? "Baik" : "Perlu bimbingan"}</span></td></tr>})}</tbody></table></div><div className="roster-footer"><span>Rata-rata kelas <strong>{(Object.values(grades).reduce((a, b) => a + Number(b), 0) / students.length).toFixed(1)}</strong></span><button className="primary-button" data-testid="grades-save-button" onClick={onSave}><Save size={16} /> Simpan nilai</button></div></section></>; }
function Schedule({ onSave }) { return <><PageTitle eyebrow="Kegiatan mengajar" title="Jadwal mengajar" description="Susun ritme hari mengajar Anda dengan jelas." action={<button className="primary-button" data-testid="schedule-add-button" onClick={onSave}><Plus size={17} /> Tambah jadwal</button>} /><section className="week-strip panel">{["Sen", "Sel", "Rab", "Kam", "Jum"].map((day, i) => <button className={i === 0 ? "selected" : ""} data-testid={`schedule-day-${i + 1}`} key={day}><strong>{day}</strong><span>{12 + i}</span></button>)}</section><section className="panel schedule-table"><PanelHeading title="Senin, 12 Mei" subtitle="3 jadwal mengajar" /><TimelineItem time="07.00 — 08.20" classNameName="7A" subject="Matematika" room="Ruang 3" active /><TimelineItem time="09.00 — 10.20" classNameName="8A" subject="Matematika" room="Ruang 5" /><TimelineItem time="11.00 — 12.20" classNameName="9A" subject="Informatika" room="Lab Komputer" /></section></>; }
function Journal({ onSave }) { return <><PageTitle eyebrow="Kegiatan mengajar" title="Jurnal mengajar" description="Simpan jejak pembelajaran dan refleksi setiap kelas." /><FormShell title="Catat jurnal baru" subtitle="Senin, 12 Mei 2025" onSave={onSave} saveLabel="Simpan jurnal"><div className="form-grid"><label className="field">Tanggal<input data-testid="journal-date-input" type="date" defaultValue="2025-05-12" /></label><label className="field">Jam ke-<input data-testid="journal-period-input" type="number" defaultValue="1" /></label><Select label="Kelas" testid="journal-class-select"><option>7A</option><option>8A</option></Select><Select label="Mata pelajaran" testid="journal-subject-select"><option>Matematika</option><option>Informatika</option></Select><label className="field full">Materi pokok<input data-testid="journal-topic-input" placeholder="Contoh: Operasi aljabar" /></label><label className="field full">Kegiatan pembelajaran<textarea data-testid="journal-activity-input" rows="4" placeholder="Tuliskan kegiatan pendahuluan, inti, dan penutup..." /></label><label className="field full">Refleksi <span className="optional">opsional</span><textarea data-testid="journal-reflection-input" rows="3" placeholder="Apa yang berjalan baik hari ini?" /></label></div></FormShell></>; }
function Reports({ onExport }) { return <><PageTitle eyebrow="Data & laporan" title="Rekap dan cetak" description="Siapkan laporan absensi, nilai, atau jurnal untuk dibagikan." action={<button className="secondary-button" data-testid="report-export-button" onClick={onExport}><FileDown size={16} /> Ekspor Excel</button>} /><div className="report-layout"><section className="panel"><PanelHeading title="Buat laporan" subtitle="Pilih data yang ingin ditampilkan" /><div className="stack-form"><Select label="Jenis laporan" testid="report-type-select"><option>Rekap absensi</option><option>Rekap nilai</option><option>Rekap jurnal mengajar</option></Select><Select label="Kelas" testid="report-class-select"><option>Semua kelas</option><option>7A</option><option>8A</option></Select><Select label="Mata pelajaran" testid="report-subject-select"><option>Semua mata pelajaran</option><option>Matematika</option></Select><Select label="Periode" testid="report-period-select"><option>Mei 2025</option><option>Semester genap 2024/2025</option></Select><button className="primary-button" data-testid="report-preview-button" onClick={onExport}><BarChart3 size={16} /> Tampilkan rekap</button></div></section><section className="panel report-preview"><div className="report-paper"><div className="report-head"><div className="brand-mark"><GraduationCap size={20} /></div><div><strong>SMP PGRI Gandoang</strong><span>Rekap Absensi Siswa</span></div></div><div className="report-line" /><div className="report-meta"><span>Periode<strong>Mei 2025</strong></span><span>Kelas<strong>7A</strong></span><span>Mapel<strong>Matematika</strong></span></div><div className="mini-bars">{[84, 96, 90, 100, 88].map((h, i) => <div key={i}><span style={{ height: `${h}%` }} /><small>{["A", "B", "C", "D", "E"][i]}</small></div>)}</div><button className="outline-button" data-testid="report-print-button" onClick={onExport}><Printer size={15} /> Pratinjau cetak</button></div></section></div></>; }
function Master({ title, icon: Icon, rows, addLabel, onSave }) { return <><PageTitle eyebrow="Administration" title={title} description="Kelola data dasar sekolah Anda." action={<button className="primary-button" data-testid="master-add-button" onClick={onSave}><Plus size={17} /> {addLabel}</button>} /><section className="panel master-panel"><div className="master-toolbar"><div className="search-field"><Search size={16} /><input data-testid="master-search-input" placeholder={`Cari ${title.toLowerCase()}...`} /></div><button className="icon-button" data-testid="master-more-button" aria-label="Opsi lainnya"><MoreHorizontal size={18} /></button></div><div className="master-list">{rows.map((row, i) => <div className="master-row" key={row}><div className="master-icon"><Icon size={18} /></div><div><strong>{row}</strong><span>{title === "Kelola Guru" ? (i === 0 ? "Administrator · 4 kelas" : "Guru mata pelajaran") : `Data aktif · diperbarui hari ini`}</span></div><button className="icon-button" data-testid={`master-row-action-${i + 1}`} aria-label={`Opsi ${row}`}><MoreHorizontal size={18} /></button></div>)}</div></section></>; }
function SettingsView({ settings, setSettings, onSave }) { return <><PageTitle eyebrow="Administration" title="Pengaturan sekolah" description="Pastikan identitas sekolah tampil rapi di setiap laporan." /><FormShell title="Identitas sekolah" subtitle="Informasi ini digunakan pada header laporan" onSave={onSave}><div className="form-grid"><label className="field full">Nama sekolah<input data-testid="settings-school-input" value={settings.school} onChange={(e) => setSettings({ ...settings, school: e.target.value })} /></label><label className="field full">Alamat<input data-testid="settings-address-input" value={settings.address} onChange={(e) => setSettings({ ...settings, address: e.target.value })} /></label><label className="field">Nama kepala sekolah<input data-testid="settings-principal-input" value={settings.principal} onChange={(e) => setSettings({ ...settings, principal: e.target.value })} /></label><label className="field">NIP kepala sekolah<input data-testid="settings-nip-input" value={settings.nip} onChange={(e) => setSettings({ ...settings, nip: e.target.value })} /></label></div></FormShell><section className="panel backup-panel"><PanelHeading title="Cadangan data" subtitle="Lindungi data administrasi Anda" action={<span className="saved-badge"><Check size={14} /> Aktif</span>} /><p>Cadangan otomatis dibuat setiap Senin pagi.</p><button className="secondary-button" data-testid="manual-backup-button" onClick={onSave}><Save size={16} /> Buat cadangan sekarang</button></section></>; }
export default App;